import {
  Community,
  Conversation,
  EventItem,
  Interest,
  NotificationItem,
  OpportunityItem,
  Post,
  Profile,
  ProjectItem,
  Purpose,
  TaskItem,
} from '../types/database';

export const INITIAL_PURPOSES: Purpose[] = [
  {
    id: 'p1',
    name: 'Learn skills',
    slug: 'learn-skills',
    description: 'Find study pods, structured challenges, and peer mentors to gain real-world ability.',
    icon: 'GraduationCap',
  },
  {
    id: 'p2',
    name: 'Find opportunities',
    slug: 'find-opportunities',
    description: 'Access verified internships, mentorships, freelance briefs, and startup roles.',
    icon: 'Compass',
  },
  {
    id: 'p3',
    name: 'Build a project',
    slug: 'build-project',
    description: 'Assemble collaborators, define milestones, and build open-source tools or products.',
    icon: 'Layers',
  },
  {
    id: 'p4',
    name: 'Meet people',
    slug: 'meet-people',
    description: 'Connect with curious thinkers, local builders, and supportive peers in your field.',
    icon: 'Users',
  },
  {
    id: 'p5',
    name: 'Sell locally',
    slug: 'sell-locally',
    description: 'Offer trusted freelance craft, technical services, or local artisan products.',
    icon: 'Store',
  },
  {
    id: 'p6',
    name: 'Support community',
    slug: 'support-community',
    description: 'Volunteer your knowledge, organize civic workshops, and help beginners level up.',
    icon: 'HeartHandshake',
  },
];

export const INITIAL_INTERESTS: Interest[] = [
  { id: 'i1', name: 'Web development', slug: 'web-development' },
  { id: 'i2', name: 'Design', slug: 'design' },
  { id: 'i3', name: 'Business', slug: 'business' },
  { id: 'i4', name: 'Music', slug: 'music' },
  { id: 'i5', name: 'Agriculture', slug: 'agriculture' },
  { id: 'i6', name: 'Gaming', slug: 'gaming' },
  { id: 'i7', name: 'Education', slug: 'education' },
  { id: 'i8', name: 'Technology', slug: 'technology' },
  { id: 'i9', name: 'Community work', slug: 'community-work' },
  { id: 'i10', name: 'Entrepreneurship', slug: 'entrepreneurship' },
  { id: 'i11', name: 'Photography', slug: 'photography' },
  { id: 'i12', name: 'Writing', slug: 'writing' },
];

export const DEMO_PROFILES: Profile[] = [
  {
    id: 'u1',
    username: 'aline_u',
    full_name: 'Aline Uwimana',
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=256&h=256&q=80',
    bio: 'Frontend developer & mentor in Kigali. Helping students build production web applications with accessible design.',
    location: 'Kigali, Rwanda',
    website: 'https://alineu.dev',
    onboarding_completed: true,
    message_privacy: 'community',
    profile_visibility: 'public',
    feed_priority: 'learning',
    selected_purposes: ['learn-skills', 'build-project', 'support-community'],
    selected_interests: ['Web development', 'Technology', 'Education'],
    created_at: '2026-01-10T09:00:00Z',
    updated_at: '2026-03-20T10:00:00Z',
    trust_points: 124,
    helpful_count: 48,
  },
  {
    id: 'u2',
    username: 'eric_n',
    full_name: 'Eric Ndayishimiye',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=256&h=256&q=80',
    bio: 'Computer science learner & university student. Building an open agri-sensor tracker for local smallholder farmers.',
    location: 'Huye, Rwanda',
    website: 'https://github.com/ericndayi',
    onboarding_completed: true,
    message_privacy: 'community',
    profile_visibility: 'public',
    feed_priority: 'learning',
    selected_purposes: ['learn-skills', 'build-project'],
    selected_interests: ['Web development', 'Agriculture', 'Technology'],
    created_at: '2026-02-01T14:30:00Z',
    updated_at: '2026-03-15T11:20:00Z',
    trust_points: 86,
    helpful_count: 22,
  },
  {
    id: 'u3',
    username: 'chantal_m',
    full_name: 'Chantal Mukamana',
    avatar_url: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=256&h=256&q=80',
    bio: 'Product designer & design educator. Organizing monthly portfolio reviews and Figma systems clinics.',
    location: 'Kigali, Rwanda',
    website: 'https://chantaldesign.co',
    onboarding_completed: true,
    message_privacy: 'community',
    profile_visibility: 'public',
    feed_priority: 'opportunities',
    selected_purposes: ['build-project', 'support-community', 'meet-people'],
    selected_interests: ['Design', 'Technology', 'Writing'],
    created_at: '2026-01-15T08:15:00Z',
    updated_at: '2026-03-22T16:00:00Z',
    trust_points: 152,
    helpful_count: 67,
  },
  {
    id: 'u4',
    username: 'david_h',
    full_name: 'David Habimana',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=256&h=256&q=80',
    bio: 'Full-stack builder & community organizer. Passionate about local open-source infrastructure and mentorship.',
    location: 'Kigali, Rwanda',
    website: 'https://davidh.rw',
    onboarding_completed: true,
    message_privacy: 'community',
    profile_visibility: 'public',
    feed_priority: 'communities',
    selected_purposes: ['find-opportunities', 'build-project', 'sell-locally'],
    selected_interests: ['Web development', 'Business', 'Entrepreneurship'],
    created_at: '2026-01-05T12:00:00Z',
    updated_at: '2026-03-24T09:40:00Z',
    trust_points: 180,
    helpful_count: 85,
  },
  {
    id: 'u5',
    username: 'grace_u',
    full_name: 'Grace Uwase',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=256&h=256&q=80',
    bio: 'Youth career coordinator & community mentor. Connecting ambitious graduates with real-world tech apprenticeships.',
    location: 'Musanze, Rwanda',
    website: 'https://graceinitiatives.org',
    onboarding_completed: true,
    message_privacy: 'community',
    profile_visibility: 'public',
    feed_priority: 'opportunities',
    selected_purposes: ['find-opportunities', 'support-community'],
    selected_interests: ['Education', 'Community work', 'Entrepreneurship'],
    created_at: '2026-01-20T10:30:00Z',
    updated_at: '2026-03-25T14:10:00Z',
    trust_points: 140,
    helpful_count: 53,
  },
];

export const DEMO_COMMUNITIES: Community[] = [
  {
    id: 'c1',
    slug: 'rwanda-it-learners',
    name: 'Rwanda IT Learners',
    description: 'Peer-to-peer coding groups, beginner questions, study challenges, and local hardware troubleshooting.',
    category: 'Technology',
    location: 'Rwanda',
    cover_image_url: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=800&q=80',
    created_by: 'u1',
    visibility: 'public',
    rules: '1. Be constructive and kind to novices. 2. Post actionable questions with code snippets. 3. Help review PRs and offer patient answers.',
    created_at: '2026-01-10T10:00:00Z',
    member_count: 342,
    is_joined: true,
  },
  {
    id: 'c2',
    slug: 'web-builders',
    name: 'Web Builders',
    description: 'Crafting accessible websites, React & Next.js systems, and modern web applications that solve real needs.',
    category: 'Web development',
    location: 'Global / Hybrid',
    cover_image_url: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=800&q=80',
    created_by: 'u4',
    visibility: 'public',
    rules: '1. Share working code, not hype. 2. Respect accessibility standards (WCAG AA). 3. Constructive architectural teardowns only.',
    created_at: '2026-01-12T11:00:00Z',
    member_count: 289,
    is_joined: true,
  },
  {
    id: 'c3',
    slug: 'kigali-creators',
    name: 'Kigali Creators',
    description: 'Local UI/UX designers, illustrators, videographers, and storytellers collaborating on cultural and tech projects.',
    category: 'Design & Arts',
    location: 'Kigali, Rwanda',
    cover_image_url: 'https://images.unsplash.com/photo-1542744094-3a31f272c490?auto=format&fit=crop&w=800&q=80',
    created_by: 'u3',
    visibility: 'public',
    rules: '1. Respect intellectual property. 2. Provide detailed design feedback. 3. Give credit where due on team collabs.',
    created_at: '2026-01-14T12:30:00Z',
    member_count: 195,
    is_joined: false,
  },
  {
    id: 'c4',
    slug: 'student-opportunities',
    name: 'Student Opportunities',
    description: 'Curated internships, mentorship pairings, scholarship alerts, and campus hackathon teams.',
    category: 'Education & Careers',
    location: 'East Africa',
    cover_image_url: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=800&q=80',
    created_by: 'u5',
    visibility: 'public',
    rules: '1. No paid application scams or spam. 2. State clear compensation/stipend info. 3. Post questions freely about resumes.',
    created_at: '2026-01-16T15:00:00Z',
    member_count: 512,
    is_joined: true,
  },
  {
    id: 'c5',
    slug: 'entrepreneurs-network',
    name: 'Entrepreneurs Network',
    description: 'Founders, small business owners, and operators exchanging operational playbooks and partnership leads.',
    category: 'Entrepreneurship',
    location: 'Rwanda',
    cover_image_url: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=800&q=80',
    created_by: 'u4',
    visibility: 'public',
    rules: '1. Focus on operational realities and real unit economics. 2. Protect confidential ideas. 3. Celebrate team milestones.',
    created_at: '2026-01-18T16:00:00Z',
    member_count: 178,
    is_joined: false,
  },
];

export const DEMO_POSTS: Post[] = [
  {
    id: 'post-1',
    author_id: 'u2',
    community_id: 'c1',
    post_type: 'help_request',
    body: 'Hello everyone! I am working on my first responsive layout with HTML and CSS Flexbox for an agri-sensor portal. I am having trouble keeping the sidebar navigation fixed while letting the sensor readings table scroll smoothly on smaller laptop screens without overflowing. Could anyone recommend the cleanest standard CSS approach or review my snippet?',
    visibility: 'public',
    urgency: 'this_week',
    category: 'Web development',
    skill_level: 'Beginner',
    tags: ['CSS Flexbox', 'Responsive Design', 'HTML'],
    created_at: '2026-09-28T04:30:00Z',
    updated_at: '2026-09-28T04:30:00Z',
    reactions: {
      helpful: 8,
      learned: 4,
      interested: 6,
      trusted: 3,
      needs_checking: 0,
    },
    user_reactions: ['helpful'],
    comments_count: 4,
    is_saved: true,
    feed_reasons: [
      'You joined Rwanda IT Learners',
      'You selected Web Development as an interest',
      'Matches your goal to learn skills',
    ],
  },
  {
    id: 'post-2',
    author_id: 'u1',
    community_id: 'c1',
    post_type: 'resource',
    body: 'Reminder for the community: We have our weekly Python & Data Structures study session happening today at 5:00 PM CAT. We will walk through list comprehensions and real-world file parsing. We have prepared an interactive Git workbook with zero-setup browser notebooks. Everyone is welcome, no prior experience needed!',
    visibility: 'public',
    category: 'Technology',
    skill_level: 'All Levels',
    tags: ['Python', 'Study Group', 'Live Session'],
    created_at: '2026-09-28T02:15:00Z',
    updated_at: '2026-09-28T02:15:00Z',
    reactions: {
      helpful: 19,
      learned: 12,
      interested: 15,
      trusted: 14,
      needs_checking: 0,
    },
    user_reactions: ['interested', 'trusted'],
    comments_count: 7,
    is_saved: false,
    feed_reasons: [
      'You joined Rwanda IT Learners',
      'This study event is happening today at 5:00 PM',
      'Created by Aline Uwimana, a mentor in your community',
    ],
  },
  {
    id: 'post-3',
    author_id: 'u3',
    community_id: 'c3',
    post_type: 'update',
    body: 'We just wrapped up our design system sprint for the Kigali Community Library open catalog. We focused entirely on high contrast typography and zero layout shift on 3G mobile connections. Check out the project board to test out the live Figma tokens and accessible button components. Feedback from readers and developers is warmly welcome!',
    visibility: 'public',
    category: 'Design',
    skill_level: 'Intermediate',
    tags: ['UI/UX', 'Design Systems', 'Accessibility'],
    created_at: '2026-09-27T14:00:00Z',
    updated_at: '2026-09-27T14:00:00Z',
    reactions: {
      helpful: 14,
      learned: 9,
      interested: 11,
      trusted: 8,
      needs_checking: 1,
    },
    user_reactions: ['learned'],
    comments_count: 5,
    is_saved: false,
    feed_reasons: [
      'Matches your interest in Design and Technology',
      'Related to active project: Kigali Transit & Library Map',
    ],
  },
  {
    id: 'post-4',
    author_id: 'u5',
    community_id: 'c4',
    post_type: 'resource',
    body: 'Verified Opportunity Alert: The Rwanda Health-Tech Lab is offering a 3-month paid apprenticeship for junior UI/UX designers and frontend apprentices. The team provides 1-on-1 mentorship, health insurance, and hands-on participation in maternal clinic workflows. Application deadline is in 14 days.',
    visibility: 'public',
    category: 'Education',
    skill_level: 'Entry-level',
    tags: ['Internship', 'Mentorship', 'Career'],
    created_at: '2026-09-27T09:45:00Z',
    updated_at: '2026-09-27T09:45:00Z',
    reactions: {
      helpful: 24,
      learned: 5,
      interested: 31,
      trusted: 20,
      needs_checking: 0,
    },
    user_reactions: ['interested'],
    comments_count: 8,
    is_saved: true,
    feed_reasons: [
      'You joined Student Opportunities',
      'You selected Find Opportunities as a primary purpose',
      'Matches skills in Web development and Design',
    ],
  },
];

export const DEMO_EVENTS: EventItem[] = [
  {
    id: 'e1',
    creator_id: 'u1',
    community_id: 'c1',
    title: 'Python Study Session: Hands-on Data Parsing',
    description: 'A practical 90-minute live session where we build a simple CSV parser in Python together. Bring your laptop and your questions! We will cover dictionaries, error handling, and clean code.',
    start_at: '2026-09-28T17:00:00Z',
    end_at: '2026-09-28T18:30:00Z',
    event_mode: 'online',
    meeting_url: 'https://meet.jit.si/rwanda-it-python-pod',
    capacity: 40,
    visibility: 'public',
    created_at: '2026-09-20T10:00:00Z',
    attendees_count: 28,
    user_rsvp: 'going',
  },
  {
    id: 'e2',
    creator_id: 'u3',
    community_id: 'c3',
    title: 'Community Design Workshop & Portfolio Clinic',
    description: 'In-person peer feedback session in Kigali. Bring 1 project or Figma frame you want constructive feedback on from senior UI/UX practitioners. Refreshments provided.',
    start_at: '2026-10-02T14:00:00Z',
    end_at: '2026-10-02T17:00:00Z',
    event_mode: 'in_person',
    location: 'Norrsken House Kigali, Town Hall Room, KG 7 Ave',
    capacity: 30,
    visibility: 'public',
    created_at: '2026-09-21T12:00:00Z',
    attendees_count: 19,
    user_rsvp: 'interested',
  },
  {
    id: 'e3',
    creator_id: 'u4',
    community_id: 'c2',
    title: 'Web Builders Open Office Hours: Clean State Architecture',
    description: 'Casual Q&A on managing complex state in React, choosing between TanStack Query and local state, and preventing re-render bugs. Drop in anytime with code.',
    start_at: '2026-10-05T16:00:00Z',
    end_at: '2026-10-05T17:30:00Z',
    event_mode: 'online',
    meeting_url: 'https://meet.jit.si/web-builders-office-hours',
    capacity: 50,
    visibility: 'public',
    created_at: '2026-09-22T08:00:00Z',
    attendees_count: 35,
    user_rsvp: 'cannot_attend',
  },
];

export const DEMO_PROJECTS: ProjectItem[] = [
  {
    id: 'proj-1',
    creator_id: 'u4',
    community_id: 'c2',
    title: 'Open Agri-Sensor Dashboard',
    goal: 'Enable cooperative farmers to monitor soil moisture and temperature using low-cost ESP32 hardware and an open web interface.',
    description: 'We are building an open-source progressive web application and telemetry system to visualize sensor nodes with zero cloud subscription fees. We are actively looking for frontend developers to build clean charts and field testing volunteers.',
    status: 'active',
    start_date: '2026-09-10',
    target_date: '2026-11-15',
    visibility: 'public',
    required_skills: ['React', 'TypeScript', 'Tailwind CSS', 'IoT Basics'],
    created_at: '2026-09-10T10:00:00Z',
    members_count: 6,
    is_member: true,
    progress: 65,
    tasks: [
      {
        id: 't1',
        project_id: 'proj-1',
        assignee_id: 'u2',
        title: 'Set up simulated MQTT telemetry packets',
        description: 'Mock 3 sensor nodes sending hourly soil metrics via JSON payloads.',
        status: 'done',
        due_date: '2026-09-25',
        created_at: '2026-09-12T10:00:00Z',
      },
      {
        id: 't2',
        project_id: 'proj-1',
        assignee_id: 'u1',
        title: 'Build high-contrast data chart component',
        description: 'Visualize 24-hour moisture readings with accessible focus states.',
        status: 'in_progress',
        due_date: '2026-10-03',
        created_at: '2026-09-14T10:00:00Z',
      },
      {
        id: 't3',
        project_id: 'proj-1',
        assignee_id: 'u4',
        title: 'Document deployment steps for rural solar gateways',
        description: 'Write clear step-by-step markdown manual for field technicians.',
        status: 'todo',
        due_date: '2026-10-10',
        created_at: '2026-09-18T10:00:00Z',
      },
    ],
  },
  {
    id: 'proj-2',
    creator_id: 'u3',
    community_id: 'c3',
    title: 'Kigali Accessible Transit Guide',
    goal: 'Create clear, community-validated walking and transit guides for youth and commuters across Kigali.',
    description: 'A collaborative civic mapping effort to document pedestrian crossings, lighting, wheelchair ramps, and key transit bus stops with verified photos.',
    status: 'planning',
    start_date: '2026-09-20',
    target_date: '2026-12-01',
    visibility: 'public',
    required_skills: ['UI/UX Design', 'User Research', 'OpenStreetMap', 'Community Outreach'],
    created_at: '2026-09-20T14:00:00Z',
    members_count: 4,
    is_member: false,
    progress: 20,
    tasks: [
      {
        id: 't4',
        project_id: 'proj-2',
        title: 'Interview 15 daily bus commuters at Nyabugogo terminal',
        status: 'in_progress',
        due_date: '2026-10-04',
        created_at: '2026-09-22T08:00:00Z',
      },
      {
        id: 't5',
        project_id: 'proj-2',
        title: 'Draft accessible color palette for route map',
        status: 'todo',
        due_date: '2026-10-12',
        created_at: '2026-09-23T09:00:00Z',
      },
    ],
  },
  {
    id: 'proj-3',
    creator_id: 'u1',
    community_id: 'c1',
    title: 'Beginner Coding Glossary (English & Kinyarwanda)',
    goal: 'Demystify software engineering terminology with culturally intuitive real-life analogies.',
    description: 'Building an open website where tech terms like "asynchronous", "API", and "database cache" are explained with clear diagrams and dual-language descriptions.',
    status: 'completed',
    start_date: '2026-08-01',
    target_date: '2026-09-15',
    visibility: 'public',
    required_skills: ['Technical Writing', 'Translation', 'HTML/CSS'],
    created_at: '2026-08-01T09:00:00Z',
    members_count: 8,
    is_member: true,
    progress: 100,
  },
];

export const DEMO_OPPORTUNITIES: OpportunityItem[] = [
  {
    id: 'opp-1',
    creator_id: 'u5',
    community_id: 'c4',
    title: 'Junior UI/UX Design Intern (3 Months Paid)',
    opportunity_type: 'internship',
    description: 'Join our public health initiative in Kigali. You will work alongside senior designers to create accessible patient intake screens and test prototypes with community health nurses. Monthly stipend: 350,000 RWF + transport allowance.',
    required_skills: ['Figma', 'UI/UX Design', 'User Research', 'Prototyping'],
    location: 'Kigali, Rwanda (Hybrid)',
    is_remote: true,
    deadline: '2026-10-14T23:59:59Z',
    contact_preference: 'platform',
    contact_info: 'internships@connectpurpose.org',
    status: 'open',
    created_at: '2026-09-25T11:00:00Z',
    is_saved: true,
  },
  {
    id: 'opp-2',
    creator_id: 'u4',
    community_id: 'c2',
    title: 'Open Source Frontend Mentorship Pod (Cohort 4)',
    opportunity_type: 'mentorship',
    description: 'Looking for 3 beginner-to-intermediate developers who want structured weekly guidance. We will conduct mock technical reviews, practice clean TypeScript code, and submit pull requests to open repositories together.',
    required_skills: ['JavaScript', 'TypeScript', 'React', 'Git'],
    location: 'Remote',
    is_remote: true,
    deadline: '2026-10-07T23:59:59Z',
    contact_preference: 'platform',
    contact_info: 'david@builders.rw',
    status: 'open',
    created_at: '2026-09-24T14:30:00Z',
    is_saved: false,
  },
  {
    id: 'opp-3',
    creator_id: 'u3',
    community_id: 'c3',
    title: 'Volunteer Brand Identity & Packaging Designer',
    opportunity_type: 'volunteer',
    description: 'A women-led coffee cooperative in Musanze needs support designing biodegradable packaging labels and product story cards for export. A great portfolio-building opportunity with real-world impact.',
    required_skills: ['Graphic Design', 'Packaging', 'Typography'],
    location: 'Musanze / Hybrid',
    is_remote: true,
    deadline: '2026-10-20T23:59:59Z',
    contact_preference: 'email',
    contact_info: 'coop@musanzecoffee.rw',
    status: 'open',
    created_at: '2026-09-22T09:00:00Z',
    is_saved: false,
  },
  {
    id: 'opp-4',
    creator_id: 'u2',
    community_id: 'c1',
    title: 'Collaborator Needed: ESP32 Firmware Engineer',
    opportunity_type: 'collaboration',
    description: 'Collaborate with us on the Open Agri-Sensor project. We have the breadboard prototypes ready and need someone with C++/MicroPython experience to optimize low-power sleep modes.',
    required_skills: ['C++', 'MicroPython', 'ESP32', 'Embedded Systems'],
    location: 'Huye or Remote',
    is_remote: true,
    deadline: '2026-10-18T23:59:59Z',
    contact_preference: 'platform',
    contact_info: 'eric@ndayishimiye.rw',
    status: 'open',
    created_at: '2026-09-26T16:00:00Z',
    is_saved: false,
  },
];

export const DEMO_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv-1',
    conversation_type: 'direct',
    created_at: '2026-09-26T10:00:00Z',
    other_user: DEMO_PROFILES[0], // Aline
    last_message: {
      id: 'm1',
      conversation_id: 'conv-1',
      sender_id: 'u1',
      body: 'Happy to look over your Flexbox code tonight before our 5 PM session! Send through the repo link whenever you are ready.',
      created_at: '2026-09-28T05:10:00Z',
    },
    unread_count: 1,
  },
  {
    id: 'conv-2',
    conversation_type: 'direct',
    created_at: '2026-09-24T12:00:00Z',
    other_user: DEMO_PROFILES[2], // Chantal
    last_message: {
      id: 'm2',
      conversation_id: 'conv-2',
      sender_id: 'u3',
      body: 'Thanks for sharing the transit feedback. We are incorporating the wheelchair ramp markers in the Figma map today.',
      created_at: '2026-09-27T16:45:00Z',
    },
    unread_count: 0,
  },
];

export const DEMO_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    user_id: 'u1',
    actor_id: 'u2',
    actor: DEMO_PROFILES[1],
    notification_type: 'reaction',
    entity_type: 'post',
    entity_id: 'post-2',
    message: 'found your Python Study Session announcement "Helpful"',
    is_read: false,
    created_at: '2026-09-28T05:30:00Z',
  },
  {
    id: 'notif-2',
    user_id: 'u1',
    actor_id: 'u3',
    actor: DEMO_PROFILES[2],
    notification_type: 'rsvp',
    entity_type: 'event',
    entity_id: 'e1',
    message: 'RSVPed "Going" to Python Study Session',
    is_read: false,
    created_at: '2026-09-28T03:15:00Z',
  },
  {
    id: 'notif-3',
    user_id: 'u1',
    actor_id: 'u5',
    actor: DEMO_PROFILES[4],
    notification_type: 'opportunity',
    entity_type: 'opportunity',
    entity_id: 'opp-1',
    message: 'shared a new internship matching your selected skills: Junior UI/UX Design Intern',
    is_read: true,
    created_at: '2026-09-27T10:00:00Z',
  },
];
